---

# "Even though kubeadm ships in the Kubernetes repositories, it’s important to install kubeadm manually."
# (quote from https://kubernetes.io/docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-9/)

- name: Install socat
  apt:
    name: socat

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Create installation directory for CNI plugins
  file:
    path: /opt/cni/bin
    state: directory

- name: Download the CNI plugins
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-amd64-{{ cni_version }}.tgz"
    dest: /opt/cni
    checksum: "{{ cni_checksum }}"
    mode: 0644

- name: Install the CNI plugins
  unarchive:
    src: "/opt/cni/cni-plugins-amd64-{{ cni_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes

- name: Download kubelet, kubectl, kubeadm
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/{{ item.name }}"
    dest: /usr/bin
    checksum: "{{ item.checksum }}"
    mode: 0755
  loop:
    - { name: 'kubelet', checksum: '{{ kubelet_checksum }}' }
    - { name: 'kubectl', checksum: '{{ kubectl_checksum }}' }
    - { name: 'kubeadm', checksum: '{{ kubeadm_checksum }}' }

- name: Download kubelet.service
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ kubernetes_version }}/build/debs/kubelet.service"
    dest: /lib/systemd/system/
    checksum: '{{ kubelet_service_checksum }}'
    mode: 0644

- name: Create kubelet.service.d directory
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: Download kubelet.service conf
  get_url:
    url: "https://raw.githubusercontent.com/kubernetes/kubernetes/{{ kubernetes_version }}/build/debs/10-kubeadm.conf"
    dest: /etc/systemd/system/kubelet.service.d
    checksum: '{{ kubelet_service_conf_checksum }}'
    mode: 0644

- name: Create custom kubelet.service conf
  template:
    src: "11-kubeadm-custom.conf.j2"
    dest: /etc/systemd/system/kubelet.service.d/11-kubeadm-custom.conf

- name: Enable the kubelet.service
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes

# The kubelet service will not start successfully unless 'kubeadm init' was run,
# because /etc/kubernetes/pki/ca.crt is missing.
# However, 'kubeadm init' will restart the kubelet service after it generated
# the configuration.
- name: Start the kubelet.service
  systemd:
    name: kubelet
    state: started
    daemon_reload: yes
